#!/bin/bash
up="before"
since="function"
echo $up
echo $since
showuptime(){
    local up=$(uptime -p | cut -c4-)
    local since=$(uptime -s)
    cat << EOF
-----
Esta maquina ha sido levantada por ${up}
se ha corrido desde ${since}
-----
EOF
}
showuptime
echo $up
echo $since